version: "3.0"

services:
  api:
    image: node:16
    container_name: api_ebytr
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - database
    tty: true
    stdin_open: true
    command: bash
    restart: always
    ports:
      - 3000:3000
    environment:
      DB_USER: root
      DB_PASS: password
      DB_HOST: database

  database:
    image: mysql
    container_name: database_ebytr
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - 3306:3306